# Generated by Django 5.2.17 on 2026-09-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Grosary', 'Grosary'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion')], max_length=50),
        ),
    ]
