# Generated by Django 5.2.17 on 2026-09-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customer_email_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Grocery', 'Grocery'), ('Books', 'Books'), ('Medicine', 'Medicine'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion')], max_length=50),
        ),
    ]
