# Generated by Django 5.2.17 on 2026-09-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('PhonePe', 'PhonePe'), ('Paytm', 'Paytm')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('upi_id', models.CharField(max_length=100)),
                ('qr_image', models.ImageField(upload_to='upi/')),
            ],
        ),
    ]
