# Generated by Django 5.2.17 on 2026-09-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_address_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Grocery', 'Grocery'), ('Medicine', 'Medicine'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion')], max_length=50)),
                ('image', models.ImageField(upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
